#!/bin/sh
#
# GPG script to encrypt a file with our best settings.
#
# Example:
#
#     $ gpg-encrypt foo.txt
#     (prompt for password)
#     #=> foo.txt.gpg
#
#
# ## Related
#
# These commands are related:
#
#   * `gpg-encrypt`: encrypt a file using our best settings.
#  
#   * `gpg-decrypt`: decrypt a file using our best settings.
#
#   * `gpg-decrypt-solo`: decrypt a file using our best settings, with no agent.
#
# ## Settings
#
#    * Symmetric encryption, i.e. we use the same password for encryption and decryption.
#      We choose this because our users can understand symmetric more easily than asymmetic.
#
#    * Encryption using the aes256 cipher algorithm.
#      We choose this because it's a good balance of strong and portable.
#
#    * digesting using the sha256 digest algorithm.
#      We choose this because it's a good balance of strong and portable.
#
#    * No compression, because typically our files are small or already compressed.
#      We choose this to maximize portability, PGP compatibility, and speed.
#
#    * Explicit settings, rather than depending on defaults.
#
#    * Suitable for GPG v2; backwards-compatible with GPG v1 when possible.
#
# To get our settings, we use these gpg options:
#
#    --symmetric                   Encrypt with symmetric cipher only This command asks for a passphrase.
#    --cipher-algo aes256          Use AES256 as the cipher algorithm
#    --digest-algo sha256          Use SHA256 as the digest algorithm.
#    --cert-digest-algo sha256     Use SHA256 as the message digest algorithm used when signing a key.
#    --compress-algo none -z 0     Do not compress the file.
#    --s2k-mode 3                  Use passphrase mangling iteration mode.
#    --s2k-digest-algo sha256      Use SHA256 as the passphrase iteration algorithm.
#    --s2k-count 65011712          Use the maximum number of passphrase iterations.
#    --force-mdc                   Use modification detection code.
#    --quiet                       Try to be as quiet as possible.
#    --no-greeting                 Suppress the initial copyright message but do not enter batch mode.
#
#
# ## Tracking
#
#   * Command: gpg-encrypt
#   * Version: 3.0.0
#   * Created: 2010-05-20
#   * Updated: 2017-09-03
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -eu
gpg --symmetric \
    --cipher-algo aes256 \
    --digest-algo sha256 \
    --cert-digest-algo sha256 \
    --compress-algo none -z 0 \
    --s2k-mode 3 \
    --s2k-digest-algo sha512 \
    --s2k-count 65011712 \
    --force-mdc \
    --quiet --no-greeting \
    "$@"
